markdown:     rdiscount
baseurl:      /wiki
encoding:     utf-8
author:       fengqiaogang
email:        fengqiaogang@163.com
description:  wiki
keywords:     wiki fengqiaogang fengqiaogang@163.com Steel.Von
rootpath:     /wiki/
static:       /wiki/static/
#regeneration: watch