markdown:     rdiscount
baseurl:      /wiki  #网站的跟路径

source:      .       #源码路径
destination: ./_site #解析到的路径
encoding:     utf-8  #编码



host:        0.0.0.0
port:        9000   #端口

lsi:          true

exclude:      [./jekyll-start.sh,./server.js]
author:       fengqiaogang
email:        fengqiaogang@163.com
description:  wiki
keywords:     wiki fengqiaogang fengqiaogang@163.com Steel.Von
rootpath:     /wiki/
static:       /wiki/static/
#regeneration: watch